modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://kubejs.com/support?source=kubejs&mc=1902&loader=forge"
license = "GNU LGPLv3"

[[mods]]
modId = "kubejs"
version = "${version}"
displayName = "KubeJS"
authors = "LatvianModder"
description = '''
Customize your modpack or server with JavaScript!
'''
logoFile = "kubejs_logo.png"
license = "GNU LGPLv3"

[[dependencies.kubejs]]
modId = "neoforge"
type = "required"
versionRange = "[20.4.57-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejs]]
modId = "rhino"
type = "required"
versionRange = "[${min_rhino_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs]]
modId = "jei"
type = "optional"
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs]]
modId = "roughlyenoughitems"
type = "optional"
versionRange = "[9.1.572,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "kubejs-common.mixins.json"

[[mixins]]
config = "kubejs-forge.mixins.json"