modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://kubejs.com/support?source=kubejs&mc=2006&loader=neoforge"
license = "GNU LGPLv3"

[[mods]]
modId = "kubejs"
version = "${version}"
displayName = "KubeJS"
authors = "latvian.dev"
description = '''
Customize your modpack or server with JavaScript!
'''
logoFile = "kubejs_logo.png"
license = "GNU LGPLv3"
modUrl = "https://kubejs.com"
displayURL = "https://kubejs.com"
displayTest = "NONE"

[[dependencies.kubejs]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.86-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejs]]
modId = "rhino"
type = "required"
versionRange = "[${rhino_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs]]
modId = "jei"
type = "optional"
versionRange = "[19.0.0.11,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.kubejs]]
modId = "roughlyenoughitems"
type = "optional"
versionRange = "[16.0.729,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.kubejs]]
modId = "emi"
type = "optional"
versionRange = "[1.1,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "kubejs.mixins.json"